mysite/mysite/urls.py
#encoding:utf-8

from django.conf.urls import patterns, include, url

# esto ...
#from mysite.views import current_datetime, hours_ahead

# equivale a esto...
from mysite.views import * 
#con lo cual nos olvidamos la larga y tediosa declaración de importaciones de las vistas

from django.contrib import admin
from django.conf import settings
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
admin.autodiscover()

#==============================================================
# vistas genericas de objetos: tomamos el modelo "Publishers" 

from django.views.generic import list_detail
from books.models import Publisher

publisher_info = {
    'queryset': Publisher.objects.all(),
    'template_name': 'books/publisher_list.html',
}

urlpatterns = patterns('',
    (r'^publishers/$', list_detail.object_list, publisher_info)
)

#==============================================================

urlpatterns += patterns('',
	# Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),
    url(r'^admin/doc/'  , include('django.contrib.admindocs.urls')),
    url(r'^admin/'      , include(admin.site.urls)),
)

urlpatterns += patterns('',
    url(r'^time/$', current_datetime),      
    url(r'^time/plus/(\d{1,2})/$', hours_ahead), 
)

urlpatterns += patterns('books.views',
    url(r'^$'                       ,'lista_libros', name='home'),
    url(r'^books/$'                 ,'lista_libros'),
    url(r'^books/search/$'          ,'search'),
    url(r'^contact/$'               ,'contact'),
    url(r'^books/add_publisher/$'   ,'add_publisher'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^debuginfo/$', 'mysite.views.debug'),       
    )

# '^' significa que requiere que el patron concuerde con el inicio de la cadena de caracteres
# '?' significa que exige que el patron concuerde con el fin de la cadena
# si iniciamos el patron con ^ y lo finalizamos con ? nos aseguramos que la (y solo la) url /time/ concuerde.  

mysite/books/models.py
#encoding=utf-8

from django.db import models

# Create your models here.

class Publisher(models.Model):
	name 			= models.CharField(max_length=30)
	address			= models.CharField(max_length=50)
	city 			= models.CharField(max_length=60)
	state_province 	= models.CharField(max_length=30)
	country 		= models.CharField(max_length=50)
	website 		= models.URLField()
	#headshot 		= models.ImageField(upload_to='tmp')
	def __unicode__(self):
		return self.name
	class Meta:
		ordering = ['name']


class Author(models.Model):
    salutation 		= models.CharField(max_length=10)
    first_name 		= models.CharField(max_length=30)
    last_name 		= models.CharField(max_length=40)
    email 			= models.EmailField()
    def __str__(self):
    	return '%s%s'% (self.first_name, self.last_name)


class Book(models.Model):
	title 			= models.CharField(max_length=100)
	authors 		= models.ManyToManyField(Author)
	publisher 		= models.ForeignKey(Publisher)
	publication_date= models.DateField()
	def __str__(self):
		return self.title

mysite/books/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False, label='Tu e-mail address')
    message = forms.CharField(widget=forms.Textarea)

    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words!")
        return message

class addBooksPublisher(forms.Form):
	name 			= forms.CharField(widget=forms.TextInput())
	address			= forms.CharField(widget=forms.TextInput())
	city 			= forms.CharField(widget=forms.TextInput())
	state_province 	= forms.CharField(widget=forms.TextInput())
	country 		= forms.CharField(widget=forms.TextInput())
	website 		= forms.CharField(widget=forms.TextInput())

	def clean(self):
		return self.cleaned_data #retorna informacion validada x django p que el usuario no pueda poner cualquier cosa en la db

mysite/books/views.py
#encoding:utf-8

# asi debería ser mi arquitectura: from mysite.apps.books.models import Publisher
from books.models import Book
from books.models import Publisher

from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect

from django.core.mail import send_mail
from django.db.models import Q
from forms import ContactForm

from forms import addBooksPublisher

#================================================

def lista_libros(request):
	books = Book.objects.all()
	if request.user.is_authenticated():
		usuario = "Hola " + str(request.user.username)
	else:
		usuario = "es anonimo"
	return render_to_response('books/books.html',{'lista':books, 'usuario':usuario}, context_instance=RequestContext(request))

#================================================

def search(request):
	query = request.GET.get('q','') #busca el parametro 'q' que viene via get | retorna un string vacio si el parametro no fue suministrado
	if query:
		#los objetos Q se usan para contruir consultas
		#icontains es una busqueda en la que no se distinguen mayusculas de minusculas, internamente usa el operador LIKE de SQL
		#distinct elimina los duplicados
		qset = (
			Q(title__icontains=query) | 
			Q(authors__first_name__icontains=query) |
			Q(authors__last_name__icontains=query)
		)
		results = Book.objects.filter(qset).distinct()
	else:
		results = []
	return render_to_response("books/search.html",{
		"results": results,
		"query": query
	})

#================================================

def contact(request):
    info_enviado = False # todavia no se envio
    asunto  = ""
    correo  = ""
    mensaje = ""
    if request.method == 'POST':
        formulario = ContactForm(request.POST)
        if formulario.is_valid():
            info_enviado = True 
            asunto  = formulario.cleaned_data['subject']
            correo  = formulario.cleaned_data['email']
            mensaje = formulario.cleaned_data['message']
            """cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'noreply@example.com'),
                ['siteowner@example.com'],
            )
            return HttpResponseRedirect('/contact/thanks/')"""
    else:
        formulario = ContactForm(
            initial={'subject': 'placeholder para subject!'}
        )
    ctx = {'form':formulario, 'info_enviado':info_enviado, 'asunto':asunto, 'correo':correo, 'mensaje':mensaje}  
    return render_to_response('books/contact_form.html', ctx, context_instance=RequestContext(request))

#================================================
#formularios que aprovechan los modelos (DRY) <- no llegue a esto todavía

def add_publisher(request):
	if request.method == 'POST':
		form = addBooksPublisher(request.POST)
		info = "Inicializando"
		if form.is_valid():
			# si es valido obtenemos los datos
			name 			= form.cleaned_data['name']
			address			= form.cleaned_data['address']
			city 			= form.cleaned_data['city']
			state_province 	= form.cleaned_data['state_province']
			country 		= form.cleaned_data['country']
			website 		= form.cleaned_data['website'] 
			p = Publisher()
			p.name 			= name
			p.address		= address
			p.city 			= city
			p.state_province= state_province
			p.country 		= country
			p.website 		= website
			p.save() #guarda el objeto
			#return HttpResponseRedirect('/add_publisher/thanks/')
			info = "se guardó satisfactoriamente!"
		else:
			info = "información con datos incorrectos"
		form = addBooksPublisher()
		ctx  = {'form':form, 'informacion':info}  
		return render_to_response('books/add_publisher.html', ctx, context_instance=RequestContext(request)) 
	else: #GET
		form = addBooksPublisher()
		ctx  = {'form':form}  
		return render_to_response('books/add_publisher.html', ctx, context_instance=RequestContext(request))

mysite/templates/books/add_publisher.html
{% extends "base.html" %}

{% block title %}add publisher{% endblock %}

{% block content %}
	<h1>Agregando publishers</h1>
	<form action="." method="POST">
		{% csrf_token %}
		<table>
			{{ form.as_table }}
		</table>	
		<p><input type="reset" value="limpiar"><input type="submit" value="Submit"/></p>
	</form>

	{% if informacion%}
		<br>
		<hr>
		<br>
		{{ informacion }}
	{% endif %}
{% endblock %}

mysite/templates/books/books.html
{% extends "base.html" %}

{% block title %}Libros{% endblock %}

{% block content %}
	<ul id="lista">	
	{% for book in lista %}		
		<li>
			<h3>{{book.title}}</h3> 
		</li>	
	{% endfor %}
	</ul>
	<hr>
	{{usuario}}
{% endblock %}

	

mysite/templates/books/chichan_form.html
{% extends "base.html" %}

{% block title %}contact us{% endblock %}

{% block content %}

    <h1>Contact us</h1>
    {% if errors %}
        <ul>
            {% for error in errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form action="" method="post">{% csrf_token %}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

mysite/templates/books/contact.html
{% extends "base.html" %}

{% block title %}contact us{% endblock %}

{% block content %}
<form action="." method="POST">
	<!--<table>
		{{ form.as_table }}
		form es nuestra instancia de ContactForm que fue pasada al render_to_response
		as_table es un método de ese objeto que reproduce el formulario comom una secuencia de renglones de una tabla (también: as_ul, as_p)
		Estas soluciones están bien para probar cosas rápido pero no para producción.
	</table> -->
	<div class="fieldWrapper">
		{{ form.topic.errors }}
		<label for='id_topic'>Kind of feedback:</label>
		{{ form.topic|escape }}
	</div>
	<div class="fieldWrapper">
		{{ form.message.errors }}
		<label for='id_message'>Your message:</label>
		{{ form.message|escape }}
	</div>
	<div class="fieldWrapper">
		{{ form.sender.errors }}
		<label for='id_sender'>Your email(optional):</label>
		{{ form.sender|escape }}
	</div>
	<p><input type="submit" value="Submit"/></p>
</form>
<!--
Las tags <table> y <form> no se incluyen por lo que debemos colocarlas nosotros
-->
<b>Este momento: </b> 
{% endblock %}

mysite/templates/books/contact_form.html
{% extends "base.html" %}

{% block title %}contact us{% endblock %}

{% block content %}

    <h1>Contact us</h1>

    {% if info_enviado %}
        <p>Gracias por comunicarse con nosotros, brevemente tendrá una respuesta</p>
        <p><b>asunto:  </b>{{ asunto }}</p>
        <p><b>correo:  </b>{{ correo }}</p>
        <p><b>mensaje: </b>{{ mensaje }}</p>
    {% else %}
        <form action="." method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>
    {% endif %}

{% endblock %}

mysite/templates/books/publisher_list.html
{% extends "base.html" %}

{% block title %}Publishers{% endblock %}

{% block content %}
	<h2>Publishers</h2>
	<hr>
	<ul>	
	{% for publisher in object_list %}		
		<li>
			<p>
				<a href="{{publisher.website}}" target="_blank">
					<strong style="text-transform:capitalize">{{publisher.name}}</strong>
				</a>
				: 
				{{publisher.address}}, 
				{{publisher.city}},  
				{{publisher.state_province}}, 
				{{publisher.country}}, 
			</p>
			<hr>
		</li>	
	{% endfor %}
	</ul>
{% endblock %}

	

mysite/templates/books/search.html
{% extends "base.html" %}

{% block title %}Busqueda {% if query %}Results{% endif %}{% endblock %}

{% block content %}
	<h1>Busqueda</h1>
	<form action="." method="GET"> <!-- el . hace referencia a la url actual-->
		<label for="q">Buscar: </label>
		<input type="text" name="q" value="{{ query|escape }}"></input> <!-- volvemos a insertar el texto de la consulta para permitir refinar facilmente la misma-->
		<input type="submit" value="Buscar"></input>
	</form>
	
	{% if query %}
		<!-- el filtro escape nos asegura que descartará las busquedas maliciosas -->
		<h2>Resultados para "{{ query|escape }}":</h2>
		{% if results %}
			<ul>
				{% for book in results %}
				<li>{{ book|escape }} {{ author }}</li>
				{% endfor %}
			</ul>
		{% else%}
			<p>No se encontraron libros</p>
		{% endif %}
	{% endif %}
{% endblock %}

	